### ISSUE TITLE
#6 main Debuging und Projekt zum Laufen bringen

### ISSUE THREAD

**Issue by tupaken** [tupaken/CRM_learn#8]
### 📦 Projekt-Setup

- Backend: AdonisJS v3.2.1
- Frontend: Nuxt 3.17.5
- Node.js: v18.20.8 (via Docker)
- Docker Compose mit Services `backend` und `frontend`

---

### 🧪 Reproduktionsschritte

1. Projekt clonen
2. `.env` für Backend unter `./docs/backend/.env` anlegen:
   ```env
   HOST=0.0.0.0
   PORT=3333
   NODE_ENV=development
   APP_KEY=1234
   ```
3. `docker-compose up --build` ausführen

---

#### 🔸 1. `.env` wird nicht gefunden

```bash
Error: ENOENT: no such file or directory, open '/app/.env'
```

#### 🔸 2. `export default` verursacht Fehler

```js
export default corsConfig
         ^^^^^^
SyntaxError: Unexpected token 'export'
```

#### 🔸 3. `ace` fehlt (AdonisJS CLI wird nicht gefunden)

```bash
Error: Cannot find module '/Users/.../ace'
```

#### 🔸 4. Container exited sofort nach dem Start

```bash
erp-backend exited with code 0
```

#### 🔸 5. Module `Express` oder `Server` wird nicht gefunden

```bash
Error: Cannot find module 'Express'
Error: Cannot find module 'Server'
```

---

#### 🔸 1. Fehler durch veraltetes `@nuxtjs/axios`

```bash
Cannot read properties of undefined (reading 'options')
```

#### 🔸 2. `<Nuxt>` Komponente nicht gefunden

```bash
[Vue warn]: Failed to resolve component: Nuxt
```

#### 🔸 3. `<NuxtPage />` fehlt

```bash
[nuxt] Your project has pages but the <NuxtPage /> component has not been used.
```

#### 🔸 4. Route `/health` wird nicht gefunden

```bash
[Vue Router warn]: No match found for location with path "/health"
```

---

#### `docker-compose.yml` (Auszug)

```yaml
services:
  backend:
    build:
      context: ./docs/backend
    container_name: erp-backend
    ports:
      - "3333:3333"
    env_file:
      - ./docs/backend/.env
    volumes:
      - ./docs/backend/.env:/app/.env
  frontend:
    build:
      context: ./docs/frontend
    container_name: erp-frontend
    ports:
      - "8000:3000"
    env_file:
      - ./docs/frontend/.env
networks:
  erp-dev-network:
    driver: bridge
```

#### `Dockerfile` (Backend)

```dockerfile
FROM node:18-alpine
RUN apk add --no-cache git bash
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3333
CMD ["npm", "run", "serve:dev"]
```

#### `.env` (Beispiel)

```env
HOST=0.0.0.0
PORT=3333
NODE_ENV=development
APP_KEY=1234
```

#### `server.js` (Ausschnitt)

```js
'use strict'

const http = require('./bootstrap/http')
http(function () {
  use('Event').fire('Http.start')
})

const express = use('Express') // Fehlerquelle
const swaggerUi = require('swagger-ui-express')
const swaggerSpec = require('./devtools/swagger')

const Server = use('Server') // Fehlerquelle
const expressApp = Server.getInstance()

expressApp.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec))
```

#### `package.json` (Backend)

```json
{
  "name": "adonis-app",
  "version": "3.2.1",
  "main": "server.js",
  "scripts": {
    "serve:dev": "nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js"
  },
  "dependencies": {
    "adonis-ace": "^3.0.7",
    "adonis-auth": "^1.0.5",
    "adonis-commands": "^2.1.5",
    "adonis-fold": "^3.0.3",
    "adonis-framework": "^3.0.10",
    "adonis-lucid": "^3.0.14",
    "adonis-middleware": "^1.0.11",
    "adonis-websocket": "^1.0.3",
    "express": "^5.1.0",
    "swagger-jsdoc": "^6.2.8",
    "swagger-ui-express": "^5.0.1"
  }
}
```

---

### ✅ Erwartetes Verhalten

- Backend startet erfolgreich auf `http://localhost:3333`
- Swagger erreichbar unter `/docs`
- Frontend unter `http://localhost:3000` ohne Fehlermeldungen
- Kein "Cannot find module", keine Vue-Komponenten- oder Router-Warnungen
